language: android
addons:
  apt:
  packages:
  - w3m
env:
  global:
  - ANDROID_TARGET=android-22
  - ANDROID_ABI=armeabi-v7a
  - ADB_INSTALL_TIMEOUT=12
jdk: openjdk10
script:
  - jdk_switcher use openjdk10
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --target $JAVA_HOME

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - extra-google-m2repository
  - extra-android-m2repository
  - android-22
  - android-28
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew clean build"
- if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
  ./gradlew app:publishReleaseApk;
  fi
before_install:
- # yes | sdkmanager "platforms;android-29"
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d

